# WARNING: This file is auto-generated from an OpenAPI schema.
# DO NOT EDIT THIS FILE DIRECTLY.
# To modify the schema, update the YAML in ./yoku/schemas/openapi/ and run
# `make models` (scripts/generate_models.py) from the repo root.


from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict

from yoku.schemas._fields import doc_field


class Primitive(StrEnum):
    """The canonical kinds the agent reasons over (the `domain` field)."""

    WORK_ITEM = "work_item"
    PULL_REQUEST = "pull_request"
    CONVERSATION = "conversation"
    DOCUMENT = "document"
    EVENT = "event"
    PERSON = "person"


_PRIMITIVES = [p.value for p in Primitive]


class BaseDoc(BaseModel):
    """The core every canonical document shares, regardless of primitive. The agent filters by `domain` (the kind), `type` (the variant), and `provider` (the vendor). `refs` carries cross-source links in the same `provider/native_key` namespace as `key`, so the delivery chain survives the projection."""

    model_config = ConfigDict(extra="allow")

    key: str = doc_field(
        "Canonical key 'provider/native_key', e.g. 'github/AsatoCorp/agent-svc#173'.",
        default=...,
        display=True,
    )
    provider: str = doc_field(
        "Source system that produced this doc, e.g. 'jira' | 'github' | 'slack'.",
        default=...,
        display=True,
        filter_arg="provider",
    )
    domain: str = doc_field(
        "The primitive / kind this doc belongs to.",
        default=...,
        display=True,
        enum=_PRIMITIVES,
        filter_arg="domain",
    )
    type: str | None = doc_field(
        "Variant within the primitive, e.g. 'ticket' | 'incident' | 'message'.",
        display=True,
        filter_arg="type",
    )
    title: str | None = doc_field("Short title / summary.", display=True)
    body: str | None = doc_field("Full text body.")
    author: str | None = doc_field(
        "Author / owner — canonical email or login (auto-resolved).",
        display=True,
        filter_arg="author",
        filter_kind="user",
    )
    status: str | None = doc_field(
        "Domain-normalized status, e.g. 'merged' | 'Done' | 'open'.",
        display=True,
        filter_arg="status",
    )
    url: str | None = doc_field("Browser URL for the item.", display=True)
    created: str | None = doc_field("ISO-8601 (or source-native) creation timestamp.")
    updated: str | None = doc_field(
        "ISO-8601 (or source-native) last-updated timestamp.", display=True
    )
    refs: list[str] = doc_field(
        "Canonical keys of linked items across sources (the delivery-chain edges).",
        default_factory=list,
        display=True,
        filter_arg="has_refs",
        filter_kind="has_refs",
    )
    text: str | None = doc_field("Embed-ready blob (title + body).")
