# WARNING: This file is auto-generated from an OpenAPI schema.
# DO NOT EDIT THIS FILE DIRECTLY.
# To modify the schema, update the YAML in ./yoku/schemas/openapi/ and run
# `make models` (scripts/generate_models.py) from the repo root.


from __future__ import annotations

from pydantic import ConfigDict

from yoku.schemas._fields import doc_field
from yoku.schemas._generated.base import BaseDoc


class Conversation(BaseDoc):
    """People exchanging text over time — Slack/Teams message, email, transcript."""

    model_config = ConfigDict(extra="allow")

    channel: str | None = doc_field(
        "Channel name without '#', e.g. 'engineering'.", display=True, filter_arg="channel"
    )
    channel_id: str | None = doc_field("Native channel id.")
    channel_type: str | None = doc_field(
        "Conversation medium: 'channel' | 'dm' | 'email' | 'meeting'.", filter_arg="channel_type"
    )
    thread_ts: str | None = doc_field("Parent thread timestamp, if a reply.", display=True)
    reply_count: int = doc_field("Number of thread replies.", default=0)
