# WARNING: This file is auto-generated from an OpenAPI schema.
# DO NOT EDIT THIS FILE DIRECTLY.
# To modify the schema, update the YAML in ./yoku/schemas/openapi/ and run
# `make models` (scripts/generate_models.py) from the repo root.


from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from yoku.schemas._fields import doc_field


class Conversation(BaseModel):
    """People exchanging text over time — Slack/Teams message, email, transcript."""

    model_config = ConfigDict(extra="allow")

    key: str = doc_field(
        "Canonical key 'provider/native_key', e.g. 'slack/C123/1234567890.123456'.",
        default=...,
        display=True,
    )
    provider: str = doc_field(
        "Source system that produced this doc, e.g. 'slack'.",
        default=...,
        display=True,
        filter_arg="provider",
    )
    domain: str = doc_field(
        "The primitive / kind this doc belongs to.",
        default=...,
        display=True,
        enum=["work_item", "pull_request", "conversation", "document", "event", "person"],
        filter_arg="domain",
    )
    type: str | None = doc_field(
        "Variant within the primitive, e.g. 'message'.", display=True, filter_arg="type"
    )
    title: str | None = doc_field("Short title / summary.", display=True)
    body: str | None = doc_field("Full text body.")
    author: str | None = doc_field(
        "Author / owner — canonical email or login (auto-resolved).",
        display=True,
        filter_arg="author",
        filter_kind="user",
    )
    status: str | None = doc_field("Domain-normalized status.", display=True, filter_arg="status")
    url: str | None = doc_field("Browser URL for the item.", display=True)
    created: str | None = doc_field("ISO-8601 (or source-native) creation timestamp.")
    updated: str | None = doc_field(
        "ISO-8601 (or source-native) last-updated timestamp.", display=True
    )
    refs: list[str] = doc_field(
        "Canonical keys of linked items across sources.",
        default_factory=list,
        display=True,
        filter_arg="has_refs",
        filter_kind="has_refs",
    )
    text: str | None = doc_field("Embed-ready blob (title + body).")
    channel: str | None = doc_field(
        "Channel name without '#', e.g. 'engineering'.", display=True, filter_arg="channel"
    )
    channel_id: str | None = doc_field("Native channel id.")
    channel_type: str | None = doc_field(
        "Conversation medium: 'channel' | 'dm' | 'email' | 'meeting'.", filter_arg="channel_type"
    )
    thread_ts: str | None = doc_field("Parent thread timestamp, if a reply.", display=True)
    reply_count: int = doc_field("Number of thread replies.", default=0)
