# WARNING: This file is auto-generated from an OpenAPI schema.
# DO NOT EDIT THIS FILE DIRECTLY.
# To modify the schema, update the YAML in ./yoku/schemas/openapi/ and run
# `make models` (scripts/generate_models.py) from the repo root.


from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from yoku.schemas._fields import doc_field


class EntityLink(BaseModel):
    """Typed cross-source edges between canonical documents — the chain graph. One row per directed (from_key, to_key) edge, derived from each canonical document's `refs`. Join from_key/to_key against documents.key to walk the delivery chain (a PR implements a ticket, a Slack message discusses one)."""

    model_config = ConfigDict(extra="allow")

    from_key: str = doc_field(
        "Canonical key of the referring document, e.g. 'github/AsatoCorp/agent-svc#173'.",
        default=...,
        display=True,
        filter_arg="from_key",
    )
    to_key: str = doc_field(
        "Canonical key of the referenced document, e.g. 'jira/AS-1234'.",
        default=...,
        display=True,
        filter_arg="to_key",
    )
    link_type: str = doc_field(
        "Edge type: 'implements' | 'discusses' | 'tracks' | 'documents' | 'relates_to' | 'references'.",
        default="references",
        display=True,
        filter_arg="link_type",
    )
    context: str | None = doc_field("Short human-readable reason the edge exists.")
    confidence: float = doc_field("Extractor confidence in [0, 1].", default=1.0, display=True)
    extractor: str = doc_field(
        "How the edge was derived: 'refs' | 'regex' | 'metadata' | 'llm'.",
        default="refs",
        display=True,
        filter_arg="extractor",
    )
