# WARNING: This file is auto-generated from an OpenAPI schema.
# DO NOT EDIT THIS FILE DIRECTLY.
# To modify the schema, update the YAML in ./yoku/schemas/openapi/ and run
# `make models` (scripts/generate_models.py) from the repo root.


from __future__ import annotations

from pydantic import ConfigDict

from yoku.schemas._fields import doc_field
from yoku.schemas._generated.base import BaseDoc


class PullRequest(BaseDoc):
    """Code that does the work — GitHub PR, GitLab MR, Bitbucket PR."""

    model_config = ConfigDict(extra="allow")

    repo: str | None = doc_field(
        "Full repo name, e.g. 'AsatoCorp/agent-svc'.",
        display=True,
        filter_arg="repo",
        normalize="gh_repo",
    )
    number: int | None = doc_field("PR number within the repo.")
    merged: bool = doc_field(
        "Whether the PR was merged.", default=False, display=True, filter_arg="merged"
    )
    is_draft: bool = doc_field("Whether the PR is a draft.", default=False, filter_arg="is_draft")
    base: str | None = doc_field("Base branch.")
    head: str | None = doc_field("Head branch.")
    merged_at: str | None = doc_field("ISO-8601 merge timestamp.")
    comments_count: int = doc_field("Number of review/issue comments.", default=0)
    labels: list[str] = doc_field("PR labels.", default_factory=list, filter_arg="label")
