# WARNING: This file is auto-generated from an OpenAPI schema.
# DO NOT EDIT THIS FILE DIRECTLY.
# To modify the schema, update the YAML in ./yoku/schemas/openapi/ and run
# `make models` (scripts/generate_models.py) from the repo root.


from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from yoku.schemas._fields import doc_field


class PullRequest(BaseModel):
    """Code that does the work — GitHub PR, GitLab MR, Bitbucket PR."""

    model_config = ConfigDict(extra="allow")

    key: str = doc_field(
        "Canonical key 'provider/native_key', e.g. 'github/AsatoCorp/agent-svc#173'.",
        default=...,
        display=True,
    )
    provider: str = doc_field(
        "Source system that produced this doc, e.g. 'github'.",
        default=...,
        display=True,
        filter_arg="provider",
    )
    domain: str = doc_field(
        "The primitive / kind this doc belongs to.",
        default=...,
        display=True,
        enum=["work_item", "pull_request", "conversation", "document", "event", "person"],
        filter_arg="domain",
    )
    type: str | None = doc_field(
        "Variant within the primitive, e.g. 'pr'.", display=True, filter_arg="type"
    )
    title: str | None = doc_field("Short title / summary.", display=True)
    body: str | None = doc_field("Full text body.")
    author: str | None = doc_field(
        "Author / owner — canonical email or login (auto-resolved).",
        display=True,
        filter_arg="author",
        filter_kind="user",
    )
    status: str | None = doc_field(
        "Domain-normalized status, e.g. 'merged' | 'open'.", display=True, filter_arg="status"
    )
    url: str | None = doc_field("Browser URL for the item.", display=True)
    created: str | None = doc_field("ISO-8601 (or source-native) creation timestamp.")
    updated: str | None = doc_field(
        "ISO-8601 (or source-native) last-updated timestamp.", display=True
    )
    refs: list[str] = doc_field(
        "Canonical keys of linked items across sources.",
        default_factory=list,
        display=True,
        filter_arg="has_refs",
        filter_kind="has_refs",
    )
    text: str | None = doc_field("Embed-ready blob (title + body).")
    repo: str | None = doc_field(
        "Full repo name, e.g. 'AsatoCorp/agent-svc'.",
        display=True,
        filter_arg="repo",
        normalize="gh_repo",
    )
    number: int | None = doc_field("PR number within the repo.")
    merged: bool = doc_field(
        "Whether the PR was merged.", default=False, display=True, filter_arg="merged"
    )
    is_draft: bool = doc_field("Whether the PR is a draft.", default=False, filter_arg="is_draft")
    base: str | None = doc_field("Base branch.")
    head: str | None = doc_field("Head branch.")
    merged_at: str | None = doc_field("ISO-8601 merge timestamp.")
    comments_count: int = doc_field("Number of review/issue comments.", default=0)
    labels: list[str] = doc_field("PR labels.", default_factory=list, filter_arg="label")
