# WARNING: This file is auto-generated from an OpenAPI schema.
# DO NOT EDIT THIS FILE DIRECTLY.
# To modify the schema, update the YAML in ./yoku/schemas/openapi/ and run
# `make models` (scripts/generate_models.py) from the repo root.


from __future__ import annotations

from pydantic import ConfigDict

from yoku.schemas._fields import doc_field
from yoku.schemas._generated.base import BaseDoc


class WorkItem(BaseDoc):
    """A unit of tracked work — Jira/Linear ticket, GitHub issue, incident, epic."""

    model_config = ConfigDict(extra="allow")

    priority: str | None = doc_field("Priority, e.g. 'High'.", display=True, filter_arg="priority")
    issue_type: str | None = doc_field(
        "Issue type, e.g. 'Task' | 'Story' | 'Bug' | 'Epic' | 'Incident'.",
        display=True,
        filter_arg="issue_type",
    )
    epic_key: str | None = doc_field("Parent epic native key.", filter_arg="epic_key")
    parent_key: str | None = doc_field("Parent issue native key (for sub-tasks).")
    reporter: str | None = doc_field("Reporter display name.")
    labels: list[str] = doc_field("Labels.", default_factory=list, filter_arg="label")
    severity: str | None = doc_field("Severity for incidents, e.g. 'P1'.", filter_arg="severity")
    resolved: str | None = doc_field("ISO-8601 resolution timestamp, if resolved.")
