# WARNING: This file is auto-generated from an OpenAPI schema.
# DO NOT EDIT THIS FILE DIRECTLY.
# To modify the schema, update the YAML in ./yoku/schemas_openapi/ and run
# `make models` (scripts/generate_models.py) from the repo root.


from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict

from yoku.core.models._fields import doc_field


class Primitive(StrEnum):
    """The canonical kinds the agent reasons over (the `domain` field)."""

    WORK_ITEM = "work_item"
    PULL_REQUEST = "pull_request"
    CONVERSATION = "conversation"
    DOCUMENT = "document"
    EVENT = "event"
    PERSON = "person"


_PRIMITIVES = [p.value for p in Primitive]


class BaseDoc(BaseModel):
    """The core every canonical document shares, regardless of primitive. The agent filters by `domain` (the kind), `type` (the variant), and `provider` (the vendor). `refs` carries cross-source links in the same `provider/native_key` namespace as `key`, so the delivery chain survives the projection."""

    model_config = ConfigDict(extra="allow")

    key: str = doc_field(
        "Canonical key 'provider/native_key', e.g. 'github/AsatoCorp/agent-svc#173'.",
        default=...,
        display=True,
    )
    provider: str = doc_field(
        "Source system that produced this doc, e.g. 'jira' | 'github' | 'slack'.",
        default=...,
        display=True,
        filter_arg="provider",
    )
    domain: str = doc_field(
        "The primitive / kind this doc belongs to.",
        default=...,
        display=True,
        enum=_PRIMITIVES,
        filter_arg="domain",
    )
    type: str | None = doc_field(
        "Variant within the primitive, e.g. 'ticket' | 'incident' | 'message'.",
        display=True,
        filter_arg="type",
    )
    title: str | None = doc_field("Short title / summary.", display=True)
    body: str | None = doc_field("Full text body.")
    author: str | None = doc_field(
        "Author / owner — canonical email or login (auto-resolved).",
        display=True,
        filter_arg="author",
        filter_kind="user",
    )
    status: str | None = doc_field(
        "Domain-normalized status, e.g. 'merged' | 'Done' | 'open'.",
        display=True,
        filter_arg="status",
    )
    url: str | None = doc_field("Browser URL for the item.", display=True)
    created: str | None = doc_field("ISO-8601 (or source-native) creation timestamp.")
    updated: str | None = doc_field(
        "ISO-8601 (or source-native) last-updated timestamp.", display=True
    )
    refs: list[str] = doc_field(
        "Canonical keys of linked items across sources (the delivery-chain edges).",
        default_factory=list,
        display=True,
        filter_arg="has_refs",
        filter_kind="has_refs",
    )
    text: str | None = doc_field("Embed-ready blob (title + body).")


class WorkItem(BaseDoc):
    """A unit of tracked work — Jira/Linear ticket, GitHub issue, incident, epic."""

    model_config = ConfigDict(extra="allow")

    priority: str | None = doc_field("Priority, e.g. 'High'.", display=True, filter_arg="priority")
    issue_type: str | None = doc_field(
        "Issue type, e.g. 'Task' | 'Story' | 'Bug' | 'Epic' | 'Incident'.",
        display=True,
        filter_arg="issue_type",
    )
    epic_key: str | None = doc_field("Parent epic native key.", filter_arg="epic_key")
    parent_key: str | None = doc_field("Parent issue native key (for sub-tasks).")
    reporter: str | None = doc_field("Reporter display name.")
    labels: list[str] = doc_field("Labels.", default_factory=list, filter_arg="label")
    severity: str | None = doc_field("Severity for incidents, e.g. 'P1'.", filter_arg="severity")
    resolved: str | None = doc_field("ISO-8601 resolution timestamp, if resolved.")


class PullRequest(BaseDoc):
    """Code that does the work — GitHub PR, GitLab MR, Bitbucket PR."""

    model_config = ConfigDict(extra="allow")

    repo: str | None = doc_field(
        "Full repo name, e.g. 'AsatoCorp/agent-svc'.",
        display=True,
        filter_arg="repo",
        normalize="gh_repo",
    )
    number: int | None = doc_field("PR number within the repo.")
    merged: bool = doc_field(
        "Whether the PR was merged.", default=False, display=True, filter_arg="merged"
    )
    is_draft: bool = doc_field("Whether the PR is a draft.", default=False, filter_arg="is_draft")
    base: str | None = doc_field("Base branch.")
    head: str | None = doc_field("Head branch.")
    merged_at: str | None = doc_field("ISO-8601 merge timestamp.")
    comments_count: int = doc_field("Number of review/issue comments.", default=0)
    labels: list[str] = doc_field("PR labels.", default_factory=list, filter_arg="label")


class Conversation(BaseDoc):
    """People exchanging text over time — Slack/Teams message, email, transcript."""

    model_config = ConfigDict(extra="allow")

    channel: str | None = doc_field(
        "Channel name without '#', e.g. 'engineering'.", display=True, filter_arg="channel"
    )
    channel_id: str | None = doc_field("Native channel id.")
    channel_type: str | None = doc_field(
        "Conversation medium: 'channel' | 'dm' | 'email' | 'meeting'.", filter_arg="channel_type"
    )
    thread_ts: str | None = doc_field("Parent thread timestamp, if a reply.", display=True)
    reply_count: int = doc_field("Number of thread replies.", default=0)


class UnifiedDoc(WorkItem, PullRequest, Conversation):
    """Union of every primitive — the schema of the polymorphic `documents` collection. A stored document is really one primitive (its `domain` says which); this union exists so the schema registry exposes every primitive's fields as filterable on the single `documents` collection. Unset fields for a given primitive are simply absent."""

    model_config = ConfigDict(extra="allow")
