"""Generate yoku Pydantic models from the OpenAPI specs in `yoku/schemas/openapi/`.

Mirrors AsatoCorp's `schemas_openapi/ -> generated Pydantic` pattern, but emits
yoku's `doc_field(...)` (carrying the agent metadata the schema registry reads:
filter_arg / filter_kind / display / normalize / enum) rather than plain
pydantic Field — datamodel-codegen can't reproduce that.

Source of truth: the YAML. The generated `.py` files carry a DO-NOT-EDIT banner.
Run via `make models` (or `python scripts/generate_models.py`).

Supported OpenAPI subset (enough for the canonical models, kept deliberately
small): object schemas with `properties`, `required`, scalar/array types, and
`allOf` with local `$ref`s — which become Python class inheritance. The custom
`x-` field extensions map onto `doc_field` kwargs; `x-enums` renders StrEnums.
Cross-file `$ref`s (e.g. `./base.yaml#/components/schemas/BaseDoc`) are resolved
as Python imports from the corresponding generated module.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import yaml

_ROOT = Path(__file__).resolve().parent.parent
_SPEC_DIR = _ROOT / "yoku" / "schemas" / "openapi"
_OUT_DIR = _ROOT / "yoku" / "schemas" / "_generated"

_BANNER = (
    "# WARNING: This file is auto-generated from an OpenAPI schema.\n"
    "# DO NOT EDIT THIS FILE DIRECTLY.\n"
    "# To modify the schema, update the YAML in ./yoku/schemas/openapi/ and run\n"
    "# `make models` (scripts/generate_models.py) from the repo root.\n"
)

# OpenAPI scalar type -> Python annotation (without Optional wrapping).
_TYPE_MAP = {"string": "str", "integer": "int", "number": "float", "boolean": "bool"}


def _py_type(prop: dict[str, Any]) -> str:
    t = prop.get("type")
    if t == "array":
        item = _TYPE_MAP.get((prop.get("items") or {}).get("type", "string"), "str")
        return f"list[{item}]"
    return _TYPE_MAP.get(t, "str")


def _ref_name(ref: str) -> str:
    """'#/components/schemas/BaseDoc' -> 'BaseDoc'."""
    return ref.rsplit("/", 1)[-1]


def _cross_file_imports(schemas: dict[str, Any]) -> dict[str, list[str]]:
    """Returns {module_name: [ClassName, ...]} for cross-file $refs."""
    by_module: dict[str, list[str]] = {}
    for schema in schemas.values():
        for part in schema.get("allOf", []):
            ref = part.get("$ref", "")
            if "#" in ref and not ref.startswith("#"):
                file_part, fragment = ref.split("#", 1)
                module = Path(file_part).stem
                class_name = fragment.rsplit("/", 1)[-1]
                by_module.setdefault(module, [])
                if class_name not in by_module[module]:
                    by_module[module].append(class_name)
    return by_module


def _local_props(node: dict[str, Any]) -> dict[str, Any]:
    """Own (non-inherited) properties of a schema node, honouring a single allOf
    inline object. Parent `$ref`s in allOf become base classes, not fields."""
    if "allOf" in node:
        merged: dict[str, Any] = {}
        for part in node["allOf"]:
            if "$ref" not in part:
                merged.update(part.get("properties", {}))
        return merged
    return node.get("properties", {})


def _bases(node: dict[str, Any], default: str) -> list[str]:
    """Base classes: the `$ref`s named in allOf, else `default` (e.g. BaseModel)."""
    refs = [_ref_name(p["$ref"]) for p in node.get("allOf", []) if "$ref" in p]
    return refs or [default]


def _required(node: dict[str, Any]) -> set[str]:
    req: set[str] = set(node.get("required", []))
    for part in node.get("allOf", []):
        req |= set(part.get("required", []))
    return req


def _field_call(name: str, prop: dict[str, Any], required: bool, enum_ref: str | None) -> str:
    """Render one `name: type = doc_field(...)` line."""
    py = _py_type(prop)
    is_array = prop.get("type") == "array"
    args: list[str] = [repr(prop.get("description", ""))]

    if required:
        args.append("default=...")
        ann = py
    elif is_array:
        args.append("default_factory=list")
        ann = py
    elif "default" in prop:
        args.append(f"default={prop['default']!r}")
        ann = py  # has a concrete default -> not Optional
    else:
        ann = f"{py} | None"

    if prop.get("x-display"):
        args.append("display=True")
    if enum_ref:
        args.append("enum=_PRIMITIVES")
    if "x-filter-arg" in prop:
        args.append(f"filter_arg={prop['x-filter-arg']!r}")
        if prop.get("x-filter-kind"):
            args.append(f"filter_kind={prop['x-filter-kind']!r}")
    if "x-normalize" in prop:
        args.append(f"normalize={prop['x-normalize']!r}")

    return f"    {name}: {ann} = doc_field({', '.join(args)})"


def _render_enum(name: str, spec: dict[str, Any]) -> str:
    lines = [f"class {name}(StrEnum):", f'    """{spec.get("description", name)}"""', ""]
    for member, value in spec["values"].items():
        lines.append(f'    {member} = "{value}"')
    lines.append("")
    lines.append(f"_PRIMITIVES = [p.value for p in {name}]")
    return "\n".join(lines)


def _render_class(name: str, node: dict[str, Any]) -> str:
    bases = _bases(node, "BaseModel")
    required = _required(node)
    head = [
        f"class {name}({', '.join(bases)}):",
        f'    """{node.get("description", name).strip()}"""',
        "",
    ]
    if (node.get("x-config") or {}).get("extra") == "allow":
        head.append('    model_config = ConfigDict(extra="allow")')
        head.append("")
    body = [
        _field_call(fname, fprop, fname in required, fprop.get("x-enum-ref"))
        for fname, fprop in _local_props(node).items()
    ]
    if not body:  # a pure-union class (only $ref bases, no own props)
        body = ["    pass"]
    return "\n".join(head + body)


def _topo_order(schemas: dict[str, Any]) -> list[str]:
    """Emit base classes before subclasses (allOf $ref => dependency).
    Cross-file refs are external dependencies — skip them in local ordering."""
    ordered: list[str] = []
    seen: set[str] = set()

    def visit(name: str) -> None:
        if name in seen:
            return
        for base in _bases(schemas[name], "BaseModel"):
            if base in schemas:
                visit(base)
        seen.add(name)
        ordered.append(name)

    for n in schemas:
        visit(n)
    return ordered


def _generate(spec_path: Path) -> Path:
    spec = yaml.safe_load(spec_path.read_text())
    schemas = spec["components"]["schemas"]
    enums = spec.get("x-enums", {})

    parts: list[str] = [_BANNER, "", "from __future__ import annotations", ""]
    if enums:
        parts += ["from enum import StrEnum", ""]
    parts += [
        "from pydantic import BaseModel, ConfigDict",
        "",
        "from yoku.schemas._fields import doc_field",
        "",
    ]
    cross = _cross_file_imports(schemas)
    for mod, classes in sorted(cross.items()):
        parts.append(f"from yoku.schemas._generated.{mod} import {', '.join(sorted(classes))}")
    if cross:
        parts.append("")
    parts.append("")
    for ename, espec in enums.items():
        parts += [_render_enum(ename, espec), "", ""]
    for cname in _topo_order(schemas):
        parts += [_render_class(cname, schemas[cname]), "", ""]

    out = _OUT_DIR / f"{spec_path.stem}.py"
    out.write_text("\n".join(parts).rstrip() + "\n")
    return out


def main() -> None:
    _OUT_DIR.mkdir(parents=True, exist_ok=True)
    (_OUT_DIR / "__init__.py").write_text(
        '"""Generated Pydantic models — do not edit; see scripts/generate_models.py."""\n'
    )
    specs = sorted(_SPEC_DIR.glob("*.yaml"))
    if not specs:
        print("no specs found in", _SPEC_DIR)
        sys.exit(1)
    for spec_path in specs:
        out = _generate(spec_path)
        print(f"  generated {out.relative_to(_ROOT)}")


if __name__ == "__main__":
    main()
